"""driver marketplace pivot: drop negotiation tables

Revision ID: 0060daab6e0a
Revises: 92b1d38aab60
Create Date: 2026-09-24 15:29:03.483221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0060daab6e0a'
down_revision: Union[str, None] = '92b1d38aab60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_actions_order_id')

    op.drop_table('pending_actions')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index('ix_drivers_tg_user_id')
        batch_op.drop_index('ix_drivers_tg_username')

    op.drop_table('drivers')
    with op.batch_alter_table('driver_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_driver_groups_tg_chat_id')

    op.drop_table('driver_groups')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index('ix_publications_group_id')
        batch_op.drop_index('ix_publications_order_id')

    op.drop_table('publications')
    with op.batch_alter_table('driver_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_driver_responses_driver_id')
        batch_op.drop_index('ix_driver_responses_order_id')

    op.drop_table('driver_responses')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_assigned_driver_id')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('commission_paid')
        batch_op.drop_column('commission_screenshot_at')
        batch_op.drop_column('commission')
        batch_op.drop_column('handed_to_dispatcher_at')
        batch_op.drop_column('driver_confirmed_call_at')
        batch_op.drop_column('assigned_driver_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_driver_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('driver_confirmed_call_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('handed_to_dispatcher_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('commission_screenshot_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('commission_paid', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('assigned_at', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_orders_assigned_driver_id', ['assigned_driver_id'], unique=False)

    op.create_table('driver_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=False),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('requested_payment', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('agreed_payment', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_responses', schema=None) as batch_op:
        batch_op.create_index('ix_driver_responses_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_driver_responses_driver_id', ['driver_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('tg_message_id', sa.BIGINT(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('driver_payment_at_post', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('posted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('delete_failed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['driver_groups.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index('ix_publications_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_publications_group_id', ['group_id'], unique=False)

    op.create_table('driver_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tg_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('directions', sa.VARCHAR(length=512), nullable=True),
    sa.Column('rules', sa.TEXT(), nullable=True),
    sa.Column('min_interval_seconds', sa.INTEGER(), nullable=False),
    sa.Column('last_posted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_groups', schema=None) as batch_op:
        batch_op.create_index('ix_driver_groups_tg_chat_id', ['tg_chat_id'], unique=1)

    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tg_user_id', sa.BIGINT(), nullable=False),
    sa.Column('tg_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('car_model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('car_plate', sa.VARCHAR(length=32), nullable=True),
    sa.Column('photo_exterior_file_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('photo_interior_file_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('photos_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('is_blacklisted', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index('ix_drivers_tg_username', ['tg_username'], unique=False)
        batch_op.create_index('ix_drivers_tg_user_id', ['tg_user_id'], unique=1)

    op.create_table('pending_actions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), nullable=False),
    sa.Column('response_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('result_message', sa.TEXT(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index('ix_pending_actions_order_id', ['order_id'], unique=False)

    # ### end Alembic commands ###
