"""initial schema

Revision ID: 6a132147dad3
Revises: 
Create Date: 2026-09-07 16:44:21.015515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a132147dad3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('directions', sa.String(length=512), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_groups_tg_chat_id'), ['tg_chat_id'], unique=True)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('car_model', sa.String(length=128), nullable=True),
    sa.Column('car_plate', sa.String(length=32), nullable=True),
    sa.Column('photo_exterior_file_id', sa.String(length=256), nullable=True),
    sa.Column('photo_interior_file_id', sa.String(length=256), nullable=True),
    sa.Column('photos_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_tg_user_id'), ['tg_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_tg_username'), ['tg_username'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('dispatcher_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('dispatcher_username', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('pickup_at', sa.DateTime(), nullable=True),
    sa.Column('from_address', sa.String(length=512), nullable=True),
    sa.Column('to_address', sa.String(length=512), nullable=True),
    sa.Column('from_city', sa.String(length=128), nullable=True),
    sa.Column('to_city', sa.String(length=128), nullable=True),
    sa.Column('flight_or_train', sa.String(length=128), nullable=True),
    sa.Column('car_class', sa.String(length=64), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('luggage', sa.String(length=128), nullable=True),
    sa.Column('has_pets', sa.Boolean(), nullable=False),
    sa.Column('needs_child_seat', sa.Boolean(), nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('client_phone', sa.String(length=64), nullable=True),
    sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('driver_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_paid', sa.Boolean(), nullable=False),
    sa.Column('commission_screenshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'NEEDS_CLARIFICATION', 'SEARCHING', 'HAS_RESPONSES', 'DRIVER_ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('has_problem', sa.Boolean(), nullable=False),
    sa.Column('problem_note', sa.Text(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('assigned_driver_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_confirmed_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handed_to_dispatcher_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_assigned_driver_id'), ['assigned_driver_id'], unique=False)

    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.Enum('AGENT', 'LOGIST', 'DISPATCHER', 'DRIVER', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('actor_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_order_id'), ['order_id'], unique=False)

    op.create_table('driver_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('ACCEPT', 'BARGAIN', 'QUESTION', 'HOLD', 'UNCLEAR', name='responsekind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'NEGOTIATING', 'FORWARDED', 'REJECTED', 'ASSIGNED', name='responsestatus', native_enum=False, length=32), nullable=False),
    sa.Column('requested_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_responses_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_responses_order_id'), ['order_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('driver_payment_at_post', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_failed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['driver_groups.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_order_id'))
        batch_op.drop_index(batch_op.f('ix_publications_group_id'))

    op.drop_table('publications')
    with op.batch_alter_table('driver_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_responses_order_id'))
        batch_op.drop_index(batch_op.f('ix_driver_responses_driver_id'))

    op.drop_table('driver_responses')
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_logs_order_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_action'))

    op.drop_table('action_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_assigned_driver_id'))

    op.drop_table('orders')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_tg_username'))
        batch_op.drop_index(batch_op.f('ix_drivers_tg_user_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('driver_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_groups_tg_chat_id'))

    op.drop_table('driver_groups')
    # ### end Alembic commands ###
