"""add order taken_by_token for my-orders feature

Revision ID: 7607935b76de
Revises: 0060daab6e0a
Create Date: 2026-09-24 15:46:15.007149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7607935b76de'
down_revision: Union[str, None] = '0060daab6e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taken_by_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('taken_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_taken_by_token'), ['taken_by_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_taken_by_token'))
        batch_op.drop_column('taken_at')
        batch_op.drop_column('taken_by_token')

    # ### end Alembic commands ###
