"""work_groups table

Revision ID: 92b1d38aab60
Revises: ba5994838abe
Create Date: 2026-09-24 14:12:26.570879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b1d38aab60'
down_revision: Union[str, None] = 'ba5994838abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_groups_tg_chat_id'), ['tg_chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_groups_tg_chat_id'))

    op.drop_table('work_groups')
    # ### end Alembic commands ###
