"""pending_actions queue

Revision ID: ba5994838abe
Revises: 6a132147dad3
Create Date: 2026-09-08 10:42:36.419832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5994838abe'
down_revision: Union[str, None] = '6a132147dad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ASSIGN', 'COMPLETE', 'CANCEL', 'CONFIRM_PAYMENT', name='pendingactiontype', native_enum=False, length=32), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'FAILED', name='pendingactionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_actions_order_id'))

    op.drop_table('pending_actions')
    # ### end Alembic commands ###
